// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWKYAd7PgveYvihKczAo7P23BIip2AD9o',
    appId: '1:425022859882:web:e43f9bdd2d99dbc47cf813',
    messagingSenderId: '425022859882',
    projectId: 'convite-casamento-260d7',
    authDomain: 'convite-casamento-260d7.firebaseapp.com',
    storageBucket: 'convite-casamento-260d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApm1ZT99oqCNP5D3NETqs-wGty2JHrAbw',
    appId: '1:425022859882:android:999dbbdec95cd8237cf813',
    messagingSenderId: '425022859882',
    projectId: 'convite-casamento-260d7',
    storageBucket: 'convite-casamento-260d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn0bvjhoOjFRregGvOqqvwd41CgLhK8nM',
    appId: '1:425022859882:ios:1bf4bafa9ee0a95d7cf813',
    messagingSenderId: '425022859882',
    projectId: 'convite-casamento-260d7',
    storageBucket: 'convite-casamento-260d7.firebasestorage.app',
    iosBundleId: 'com.example.conviteCasamento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn0bvjhoOjFRregGvOqqvwd41CgLhK8nM',
    appId: '1:425022859882:ios:1bf4bafa9ee0a95d7cf813',
    messagingSenderId: '425022859882',
    projectId: 'convite-casamento-260d7',
    storageBucket: 'convite-casamento-260d7.firebasestorage.app',
    iosBundleId: 'com.example.conviteCasamento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWKYAd7PgveYvihKczAo7P23BIip2AD9o',
    appId: '1:425022859882:web:1caec48ac97e19ab7cf813',
    messagingSenderId: '425022859882',
    projectId: 'convite-casamento-260d7',
    authDomain: 'convite-casamento-260d7.firebaseapp.com',
    storageBucket: 'convite-casamento-260d7.firebasestorage.app',
  );
}
